### ISSUE TITLE
AES Encryption between Meteor and Node?

### ISSUE THREAD

**Issue by KyleKing** [p-j/meteor-crypto-aes#2]
I'm attempting to encrypt a string on an Arduino using AES and decrypt that string in Meteor.
This is my workflow:
Arduino -> Serial Print -> Node -> DDP -> Meteor

I’m having trouble decrypting the Meteor-encrypted string in Node and vice-versa (see code below):
I think this issue has something to do with which character sets the particular package encodes in.

``` js
// same for both
key = 'Dino';
message = 'hi';

// In the Meteor App
encrypted = CryptoJS.AES.encrypt(message, key);
console.log(encrypted.toString());
// U2FsdGVkX1/LDvfX9UaN8GQiQAW3jv9lwl4r69Gp+WI= 
decrypted = CryptoJS.AES.decrypt(encrypted, key);
console.log(decrypted.toString(CryptoJS.enc.Utf8));
// 'hi'

// In the Node App:
var CryptoJS = (require('cryptojs')).Crypto;
encrypted = CryptoJS.AES.encrypt(message, key);
console.log(encrypted.toString());
// 08EOCcMKzQUQ1ys7SVS53QmK
decrypted = CryptoJS.AES.decrypt(encrypted, key);
// console.log(decrypted.toString(CryptoJS.enc.Utf8));
console.log(decrypted.toString());
// 'hi'

// Or alternatively in the Node App:
// Source: http://lollyrock.com/articles/nodejs-encryption/
// Nodejs encryption with cbc
var crypto = require('crypto'),
    algorithm = 'aes-256-cbc',
    password = key;

function encrypt(text){
  var cipher = crypto.createCipher(algorithm,password);
  var crypted = cipher.update(text,'utf8','hex');
  crypted += cipher.final('hex');
  return crypted;
}

function decrypt(text){
  var decipher = crypto.createDecipher(algorithm,password);
  var dec = decipher.update(text,'hex','utf8');
  dec += decipher.final('utf8');
  return dec;
}

var encrypted = encrypt(message);
console.log(encrypted); // c4583f98fa8db5d84c55af297a157408
console.log(decrypt(encrypted)); // 'hi'
```
1. First off, is the data secure enough through this pathway that AES won't be needed?
2. Will your Meteor Package use CBC and PKCS7 (the defaults of CryptoJS) as the defaults for encryption?
3. Is there a better node package to use?

I figured you were much more familiar with this topic and might help direct me to the right solution.

Update: I'm still working with the code and trying to find a solution. I think it has something to do with padding, as the first characters differ in each string produced by Node.

**Comment by p-j** [comment]
Hi @KyleKing 

To answer your questions : 
1. I'm not sure I understand your pathway, where is Node runngin and why do you want to encrypt these transmissions ?
2. My package is a direct port from CryptoJS to Meteor, same code, same defaults.
3. I don't know, but I would recommend using CryptoJS on both side, it would surely be easier to get things done consistently.

**Comment by KyleKing** [comment]
HI @p-j!
1. I'm trying to send data from an arduino to my meteor app. This arduino will be receiving data from a Zigbee sensor network and will be the only one that is connected to the internet. This arduino sends the information through Serial.write that is read by a local node app. The Node app then remotely connects to my meteor app and updates the database. Does that make more sense? I'm using this [work in progress code](https://github.com/KyleKing/TeamBIKES/blob/develop/node_client.js).
   The information will include data that could be used to identify certain users, so I want to add an extra layer of security in case someone is able to intercept the node to meteor communication.
2. /3. Thanks, I'll keep trying and see if I can get it worked out

**Comment by p-j** [comment]
Well, first, I see you are using SSL between your Node.js client and your Meteor.js server. That should be sufficient to protect your information while they are transferred from your Adruino to your Meteor server. 

If you really want to use AES on top of the SSL encryption, it should be possible, and to make sure you use CBC and PKCS7 on the Meteor side, you can do it this way : 

``` javascript
var data = { message: "This is my message !", key: "This is my very secret key" };

var encrypted = CryptoJS.AES.encrypt(data.message, data.key, {
    mode: CryptoJS.mode.CBC,
    padding: CryptoJS.pad.Pkcs7
});

var decrypted = CryptoJS.AES.decrypt(encrypted, data.key, {
    mode: CryptoJS.mode.CBC,
    padding: CryptoJS.pad.Pkcs7
});

console.log(encrypted.toString());
console.log(decrypted.toString(CryptoJS.enc.Utf8));
```

I tested it on the browser as well : 

``` html
<!DOCTYPE html>
<html>
<head>
    <title>Test CryptoJS</title>
    <script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js"></script>
    <script type="text/javascript">
        var data = { message: "This is my message !", key: "This is my very secret key" };

    var encrypted = CryptoJS.AES.encrypt(data.message, data.key, {
        mode: CryptoJS.mode.CBC,
        padding: CryptoJS.pad.Pkcs7
    });

    var decrypted = CryptoJS.AES.decrypt(encrypted, data.key, {
        mode: CryptoJS.mode.CBC,
        padding: CryptoJS.pad.Pkcs7
    });

    console.log(encrypted.toString());
    console.log(decrypted.toString(CryptoJS.enc.Utf8));     

    </script>
</head>
<body>

</body>
</html>
```

If you look in the console, you'll see that it works, if then you take the result of the encoded message on the meteor side and paste it in the console of your browser like this : 

```
CryptoJS.AES.decrypt(<your encoded string>, data.key).toString(CryptoJS.enc.Utf8)
```

You should see the result.

Hope this helps.

**Comment by p-j** [comment]
Actually, it seems the problems comes from the `cryptojs` package, I tried quickly with it and its output was not decryptable, whereas with the [`crypto-js`](https://www.npmjs.com/package/crypto-js) one, it worked : 

``` javascript
var CryptoJS = require("crypto-js");

var data = { message: "This is my message !", key: "This is my very secret key" };

var encrypted = CryptoJS.AES.encrypt(data.message, data.key, {
    mode: CryptoJS.mode.CBC,
    padding: CryptoJS.pad.Pkcs7
});

var decrypted = CryptoJS.AES.decrypt(encrypted, data.key, {
    mode: CryptoJS.mode.CBC,
    padding: CryptoJS.pad.Pkcs7
});

console.log(encrypted.toString());
console.log(decrypted.toString(CryptoJS.enc.Utf8));
```

**Comment by KyleKing** [comment]
Thank you so much! That worked perfectly!

**Comment by p-j** [comment]
Happy I could help, and happy to know that my package is useful to someone else than myself :)
