### ISSUE TITLE
Non-usable in Velocity ?

### ISSUE THREAD

**Issue by Sikwan** [p-j/meteor-crypto-aes#3]
Hi Jérémie,

First of all thanks a lot for the fine package, really handy ;)

I have a slight issue when trying to code Integration tests using CryptoJS, it always send back undefined and I can see this when printing the prototype of any function:

`
 _isMockFunction: true
`

Is this intended ? Is there a way to work around it ?

Thanks !

**Comment by p-j** [comment]
Hi François,

I've never used Velocity and I'm not doing much Meteor work lately so I don't have inputs on that matter.
Do you have a repository I can have a look at ?
As a side note, I'm pretty busy currently so I may not be able to answer as fast as I would like to. I hope its not blocking you on your projects.

Thanks for reporting !

**Comment by Sikwan** [comment]
Hi again,

While doing a small project to show you what goes on, I found the issue ;) 

Here is the project: https://github.com/Sikwan/crypto-velocity

Turns out Jasmine and/or Velocity (still have to dig that) automatically mocks packages when doing Unit Tests which is good practice (never unit test something that would need integration test rights ?)

When I move the test from unit to integration, it runs perfectly.

Sorry for the disturbance !

Cheers

**Comment by p-j** [comment]
All good then !
Thanks for the feedback.
